// Emacs style mode select   -*- C++ -*- 
//-----------------------------------------------------------------------------
//
// $Id:$
//
// Copyright (C) 1993-1996 by id Software, Inc.
//
// This source is available for distribution and/or modification
// only under the terms of the DOOM Source Code License as
// published by id Software. All rights reserved.
//
// The source is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// FITNESS FOR A PARTICULAR PURPOSE. See the DOOM Source Code License
// for more details.
//
// DESCRIPTION:
//	Printed strings, french translation.
//
//-----------------------------------------------------------------------------


#ifndef __D_FRENCH__
#define __D_FRENCH__

//
// D_Main.C
//
#define FRND_DEVSTR	"MODE DEVELOPPEMENT ON.\n"
#define FRND_CDROM		"VERSION CD-ROM: DEFAULT.CFG DANS C:\\DOOMDATA\n"

//
//	M_Menu.C
//
#define FRNPRESSKEY 	"APPUYEZ SUR UNE TOUCHE."
#define FRNPRESSYN 	"APPUYEZ SUR Y OU N"
#define FRNQUITMSG		"VOUS VOULEZ VRAIMENT\nQUITTER CE SUPER JEU?"
#define FRNLOADNET 	"VOUS NE POUVEZ PAS CHARGER\nUN JEU EN RESEAU!\n\nAPPUYEZ SUR UNE TOUCHE."
#define FRNQLOADNET	"CHARGEMENT RAPIDE INTERDIT EN RESEAU!\n\nAPPUYEZ SUR UNE TOUCHE."
#define FRNQSAVESPOT	"VOUS N'AVEZ PAS CHOISI UN EMPLACEMENT!\n\nAPPUYEZ SUR UNE TOUCHE."
#define FRNSAVEDEAD 	"VOUS NE POUVEZ PAS SAUVER SI VOUS NE JOUEZ "\
"PAS!\n\nAPPUYEZ SUR UNE TOUCHE."
#define FRNQSPROMPT 	"SAUVEGARDE RAPIDE DANS LE FICHIER \n\n'%s'?\n\nAPPUYEZ SUR Y OU N"
#define FRNQLPROMPT	"VOULEZ-VOUS CHARGER LA SAUVEGARDE"\
"\n\n'%s'?\n\nAPPUYEZ SUR Y OU N"
#define FRNNEWGAME		"VOUS NE POUVEZ PAS LANCER\n"\
"UN NOUVEAU JEU SUR RESEAU.\n\nAPPUYEZ SUR UNE TOUCHE."
#define FRNNIGHTMARE	"VOUS CONFIRMEZ? CE NIVEAU EST\n"\
"VRAIMENT IMPITOYABLE!nAPPUYEZ SUR Y OU N"
#define FRNSWSTRING	"CECI EST UNE VERSION SHAREWARE DE DOOM.\n\n"\
"VOUS DEVRIEZ COMMANDER LA TRILOGIE COMPLETE.\n\nAPPUYEZ SUR UNE TOUCHE."
#define FRNMSGOFF		"MESSAGES OFF"
#define FRNMSGON		"MESSAGES ON"
#define FRNNETEND		"VOUS NE POUVEZ PAS METTRE FIN A UN JEU SUR "\
"RESEAU!\n\nAPPUYEZ SUR UNE TOUCHE."
#define FRNENDGAME		"VOUS VOULEZ VRAIMENT METTRE FIN AU JEU?\n\nAPPUYEZ SUR Y OU N"

#define FRNDOSY		"(APPUYEZ SUR Y POUR REVENIR AU OS.)"

#define FRNDETAILHI	"GRAPHISMES MAXIMUM "
#define FRNDETAILLO	"GRAPHISMES MINIMUM "
#define FRNGAMMALVL0	"CORRECTION GAMMA OFF"
#define FRNGAMMALVL1	"CORRECTION GAMMA NIVEAU 1"
#define FRNGAMMALVL2	"CORRECTION GAMMA NIVEAU 2"
#define FRNGAMMALVL3	"CORRECTION GAMMA NIVEAU 3"
#define FRNGAMMALVL4	"CORRECTION GAMMA NIVEAU 4"
#define FRNEMPTYSTRING	"EMPLACEMENT VIDE"

//
//	P_inter.C
//
#define FRNGOTARMOR	"ARMURE RECUPEREE."
#define FRNGOTMEGA		"MEGA-ARMURE RECUPEREE!"
#define FRNGOTHTHBONUS	"BONUS DE SANTE RECUPERE."
#define FRNGOTARMBONUS	"BONUS D'ARMURE RECUPERE."
#define FRNGOTSTIM		"STIMPACK RECUPERE."
#define FRNGOTMEDINEED	"MEDIKIT RECUPERE. VOUS EN AVEZ VRAIMENT BESOIN!"
#define FRNGOTMEDIKIT	"MEDIKIT RECUPERE."
#define FRNGOTSUPER	"SUPERCHARGE!"

#define FRNGOTBLUECARD	"CARTE MAGNETIQUE BLEUE RECUPEREE."
#define FRNGOTYELWCARD	"CARTE MAGNETIQUE JAUNE RECUPEREE."
#define FRNGOTREDCARD	"CARTE MAGNETIQUE ROUGE RECUPEREE."
#define FRNGOTBLUESKUL	"CLEF CRANE BLEUE RECUPEREE."
#define FRNGOTYELWSKUL	"CLEF CRANE JAUNE RECUPEREE."
#define FRNGOTREDSKULL	"CLEF CRANE ROUGE RECUPEREE."

#define FRNGOTINVUL	"INVULNERABILITE!"
#define FRNGOTBERSERK	"BERSERK!"
#define FRNGOTINVIS	"INVISIBILITE PARTIELLE "
#define FRNGOTSUIT		"COMBINAISON ANTI-RADIATIONS "
#define FRNGOTMAP		"CARTE INFORMATIQUE "
#define FRNGOTVISOR	"VISEUR A AMPLIFICATION DE LUMIERE "
#define FRNGOTMSPHERE	"MEGASPHERE!"

#define FRNGOTCLIP		"CHARGEUR RECUPERE."
#define FRNGOTCLIPBOX	"BOITE DE BALLES RECUPEREE."
#define FRNGOTROCKET	"ROQUETTE RECUPEREE."
#define FRNGOTROCKBOX	"CAISSE DE ROQUETTES RECUPEREE."
#define FRNGOTCELL		"CELLULE D'ENERGIE RECUPEREE."
#define FRNGOTCELLBOX	"PACK DE CELLULES D'ENERGIE RECUPERE."
#define FRNGOTSHELLS	"4 CARTOUCHES RECUPEREES."
#define FRNGOTSHELLBOX	"BOITE DE CARTOUCHES RECUPEREE."
#define FRNGOTBACKPACK	"SAC PLEIN DE MUNITIONS RECUPERE!"

#define FRNGOTBFG9000	"VOUS AVEZ UN BFG9000!  OH, OUI!"
#define FRNGOTCHAINGUN	"VOUS AVEZ LA MITRAILLEUSE!"
#define FRNGOTCHAINSAW	"UNE TRONCONNEUSE!"
#define FRNGOTLAUNCHER	"VOUS AVEZ UN LANCE-ROQUETTES!"
#define FRNGOTPLASMA	"VOUS AVEZ UN FUSIL A PLASMA!"
#define FRNGOTSHOTGUN	"VOUS AVEZ UN FUSIL!"
#define FRNGOTSHOTGUN2	"VOUS AVEZ UN SUPER FUSIL!"

//
// P_Doors.C
//
#define FRNPD_BLUEO	"IL VOUS FAUT UNE CLEF BLEUE"
#define FRNPD_REDO	"IL VOUS FAUT UNE CLEF ROUGE"
#define FRNPD_YELLOWO	"IL VOUS FAUT UNE CLEF JAUNE"
#define FRNPD_BLUEK     "IL VOUS FAUT UNE CLEF BLEUE"
#define FRNPD_REDK      "IL VOUS FAUT UNE CLEF ROUGE"
#define FRNPD_YELLOWK   "IL VOUS FAUT UNE CLEF JAUNE"

//
//	G_game.C
//
#define FRNGGSAVED		"JEU SAUVEGARDE."

//
//	HU_stuff.C
//
#define FRNHUSTR_MSGU	"[MESSAGE NON ENVOYE]"

#define FRNHUSTR_E1M1	"E1M1: HANGAR"
#define FRNHUSTR_E1M2	"E1M2: USINE NUCLEAIRE "
#define FRNHUSTR_E1M3	"E1M3: RAFFINERIE DE TOXINES "
#define FRNHUSTR_E1M4	"E1M4: CENTRE DE CONTROLE "
#define FRNHUSTR_E1M5	"E1M5: LABORATOIRE PHOBOS "
#define FRNHUSTR_E1M6	"E1M6: TRAITEMENT CENTRAL "
#define FRNHUSTR_E1M7	"E1M7: CENTRE INFORMATIQUE "
#define FRNHUSTR_E1M8	"E1M8: ANOMALIE PHOBOS "
#define FRNHUSTR_E1M9	"E1M9: BASE MILITAIRE "

#define FRNHUSTR_E2M1	"E2M1: ANOMALIE DEIMOS "
#define FRNHUSTR_E2M2	"E2M2: ZONE DE CONFINEMENT "
#define FRNHUSTR_E2M3	"E2M3: RAFFINERIE"
#define FRNHUSTR_E2M4	"E2M4: LABORATOIRE DEIMOS "
#define FRNHUSTR_E2M5	"E2M5: CENTRE DE CONTROLE "
#define FRNHUSTR_E2M6	"E2M6: HALLS DES DAMNES "
#define FRNHUSTR_E2M7	"E2M7: CUVES DE REPRODUCTION "
#define FRNHUSTR_E2M8	"E2M8: TOUR DE BABEL "
#define FRNHUSTR_E2M9	"E2M9: FORTERESSE DU MYSTERE "

#define FRNHUSTR_E3M1	"E3M1: DONJON DE L'ENFER "
#define FRNHUSTR_E3M2	"E3M2: BOURBIER DU DESESPOIR "
#define FRNHUSTR_E3M3	"E3M3: PANDEMONIUM"
#define FRNHUSTR_E3M4	"E3M4: MAISON DE LA DOULEUR "
#define FRNHUSTR_E3M5	"E3M5: CATHEDRALE PROFANE "
#define FRNHUSTR_E3M6	"E3M6: MONT EREBUS"
#define FRNHUSTR_E3M7	"E3M7: LIMBES"
#define FRNHUSTR_E3M8	"E3M8: DIS"
#define FRNHUSTR_E3M9	"E3M9: CLAPIERS"

#define FRNHUSTR_1		"NIVEAU 1: ENTREE "
#define FRNHUSTR_2		"NIVEAU 2: HALLS SOUTERRAINS "
#define FRNHUSTR_3		"NIVEAU 3: LE FEU NOURRI "
#define FRNHUSTR_4		"NIVEAU 4: LE FOYER "
#define FRNHUSTR_5		"NIVEAU 5: LES EGOUTS "
#define FRNHUSTR_6		"NIVEAU 6: LE BROYEUR "
#define FRNHUSTR_7		"NIVEAU 7: L'HERBE DE LA MORT"
#define FRNHUSTR_8		"NIVEAU 8: RUSES ET PIEGES "
#define FRNHUSTR_9		"NIVEAU 9: LE PUITS "
#define FRNHUSTR_10	"NIVEAU 10: BASE DE RAVITAILLEMENT "
#define FRNHUSTR_11	"NIVEAU 11: LE CERCLE DE LA MORT!"

#define FRNHUSTR_12	"NIVEAU 12: L'USINE "
#define FRNHUSTR_13	"NIVEAU 13: LE CENTRE VILLE"
#define FRNHUSTR_14	"NIVEAU 14: LES ANTRES PROFONDES "
#define FRNHUSTR_15	"NIVEAU 15: LA ZONE INDUSTRIELLE "
#define FRNHUSTR_16	"NIVEAU 16: LA BANLIEUE"
#define FRNHUSTR_17	"NIVEAU 17: LES IMMEUBLES"
#define FRNHUSTR_18	"NIVEAU 18: LA COUR "
#define FRNHUSTR_19	"NIVEAU 19: LA CITADELLE "
#define FRNHUSTR_20	"NIVEAU 20: JE T'AI EU!"

#define FRNHUSTR_21	"NIVEAU 21: LE NIRVANA"
#define FRNHUSTR_22	"NIVEAU 22: LES CATACOMBES "
#define FRNHUSTR_23	"NIVEAU 23: LA GRANDE FETE "
#define FRNHUSTR_24	"NIVEAU 24: LE GOUFFRE "
#define FRNHUSTR_25	"NIVEAU 25: LES CHUTES DE SANG"
#define FRNHUSTR_26	"NIVEAU 26: LES MINES ABANDONNEES "
#define FRNHUSTR_27	"NIVEAU 27: CHEZ LES MONSTRES "
#define FRNHUSTR_28	"NIVEAU 28: LE MONDE DE L'ESPRIT "
#define FRNHUSTR_29	"NIVEAU 29: LA LIMITE "
#define FRNHUSTR_30	"NIVEAU 30: L'ICONE DU PECHE "

#define FRNHUSTR_31	"NIVEAU 31: WOLFENSTEIN"
#define FRNHUSTR_32	"NIVEAU 32: LE MASSACRE"


#define FRNHUSTR_CHATMACRO1	"JE SUIS PRET A LEUR EN FAIRE BAVER!"
#define FRNHUSTR_CHATMACRO2	"JE VAIS BIEN."
#define FRNHUSTR_CHATMACRO3	"JE N'AI PAS L'AIR EN FORME!"
#define FRNHUSTR_CHATMACRO4	"AU SECOURS!"
#define FRNHUSTR_CHATMACRO5	"TU CRAINS!"
#define FRNHUSTR_CHATMACRO6	"LA PROCHAINE FOIS, MINABLE..."
#define FRNHUSTR_CHATMACRO7	"VIENS ICI!"
#define FRNHUSTR_CHATMACRO8	"JE VAIS M'EN OCCUPER."
#define FRNHUSTR_CHATMACRO9	"OUI"
#define FRNHUSTR_CHATMACRO0	"NON"

#define FRNHUSTR_TALKTOSELF1	"VOUS PARLEZ TOUT SEUL "
#define FRNHUSTR_TALKTOSELF2	"QUI EST LA?"
#define FRNHUSTR_TALKTOSELF3	"VOUS VOUS FAITES PEUR "
#define FRNHUSTR_TALKTOSELF4	"VOUS COMMENCEZ A DELIRER "
#define FRNHUSTR_TALKTOSELF5	"VOUS ETES LARGUE..."

#define FRNHUSTR_MESSAGESENT	"[MESSAGE ENVOYE]"

// The following should NOT be changed unless it seems
// just AWFULLY necessary

#define FRNHUSTR_PLRGREEN	"VERT: "
#define FRNHUSTR_PLRINDIGO	"INDIGO: "
#define FRNHUSTR_PLRBROWN	"BRUN: "
#define FRNHUSTR_PLRRED		"ROUGE: "
#define FRNHUSTR_PLRGOLD	"Gold: "
#define FRNHUSTR_PLRBLUE	"Blue: "
#define FRNHUSTR_PLRDKBLUE	"DkBlue: "
#define FRNHUSTR_PLRPINK	"Pink: "

#define FRNHUSTR_KEYGREEN	"g"	// french key should be "V"
#define FRNHUSTR_KEYINDIGO	"i"
#define FRNHUSTR_KEYBROWN	"b"
#define FRNHUSTR_KEYRED		"r"

//
//	AM_map.C
//

#define FRNAMSTR_FOLLOWON		"MODE POURSUITE ON"
#define FRNAMSTR_FOLLOWOFF		"MODE POURSUITE OFF"

#define FRNAMSTR_GRIDON		"GRILLE ON"
#define FRNAMSTR_GRIDOFF		"GRILLE OFF"

#define FRNAMSTR_MARKEDSPOT	"REPERE MARQUE "
#define FRNAMSTR_MARKSCLEARED	"REPERES EFFACES "

//
//	ST_stuff.C
//

#define FRNSTSTR_MUS		"CHANGEMENT DE MUSIQUE "
#define FRNSTSTR_NOMUS		"IMPOSSIBLE SELECTION"
#define FRNSTSTR_DQDON		"INVULNERABILITE ON "
#define FRNSTSTR_DQDOFF		"INVULNERABILITE OFF"

#define FRNSTSTR_KFAADDED		"ARMEMENT MAXIMUM! "
#define FRNSTSTR_FAADDED		"ARMES (SAUF CLEFS) AJOUTEES"

#define FRNSTSTR_NCON		"BARRIERES ON"
#define FRNSTSTR_NCOFF		"BARRIERES OFF"

#define FRNSTSTR_BEHOLD		" inVuln, Str, Inviso, Rad, Allmap, or Lite-amp"
#define FRNSTSTR_BEHOLDX		"AMELIORATION ACTIVEE"

#define FRNSTSTR_CHOPPERS		"... DOESN'T SUCK - GM"
#define FRNSTSTR_CLEV		"CHANGEMENT DE NIVEAU..."

//
//	F_Finale.C
//
#define FRNE1TEXT	"APRES AVOIR VAINCU LES GROS MECHANTS\n"\
"ET NETTOYE LA BASE LUNAIRE, VOUS AVEZ\n"\
"GAGNE, NON? PAS VRAI? OU EST DONC VOTRE\n"\
" RECOMPENSE ET VOTRE BILLET DE\n"\
"RETOUR? QU'EST-QUE CA VEUT DIRE?CE"\
"N'EST PAS LA FIN ESPEREE!\n"\
"\n" \
"CA SENT LA VIANDE PUTREFIEE, MAIS\n"\
"ON DIRAIT LA BASE DEIMOS. VOUS ETES\n"\
"APPAREMMENT BLOQUE AUX PORTES DE L'ENFER.\n"\
"LA SEULE ISSUE EST DE L'AUTRE COTE.\n"\
"\n"\
"POUR VIVRE LA SUITE DE DOOM, JOUEZ\n"\
"A 'AUX PORTES DE L'ENFER' ET A\n"\
"L'EPISODE SUIVANT, 'L'ENFER'!\n"
				
#define FRNE2TEXT	"VOUS AVEZ REUSSI. L'INFAME DEMON\n"\
"QUI CONTROLAIT LA BASE LUNAIRE DE\n"\
"DEIMOS EST MORT, ET VOUS AVEZ\n"\
"TRIOMPHE! MAIS... OU ETES-VOUS?\n"\
"VOUS GRIMPEZ JUSQU'AU BORD DE LA\n"\
"LUNE ET VOUS DECOUVREZ L'ATROCE\n"\
"VERITE.\n" \
"\n"\
"DEIMOS EST AU-DESSUS DE L'ENFER!\n"\
"VOUS SAVEZ QUE PERSONNE NE S'EN\n"\
"EST JAMAIS ECHAPPE, MAIS CES FUMIERS\n"\
"VONT REGRETTER DE VOUS AVOIR CONNU!\n"\
"VOUS REDESCENDEZ RAPIDEMENT VERS\n"\
"LA SURFACE DE L'ENFER.\n"\
"\n" \
"VOICI MAINTENANT LE CHAPITRE FINAL DE\n"\
"DOOM! -- L'ENFER."

#define FRNE3TEXT	"LE DEMON ARACHNEEN ET REPUGNANT\n"\
"QUI A DIRIGE L'INVASION DES BASES\n"\
"LUNAIRES ET SEME LA MORT VIENT DE SE\n"\
"FAIRE PULVERISER UNE FOIS POUR TOUTES.\n"\
"\n"\
"UNE PORTE SECRETE S'OUVRE. VOUS ENTREZ.\n"\
"VOUS AVEZ PROUVE QUE VOUS POUVIEZ\n"\
"RESISTER AUX HORREURS DE L'ENFER.\n"\
"IL SAIT ETRE BEAU JOUEUR, ET LORSQUE\n"\
"VOUS SORTEZ, VOUS REVOYEZ LES VERTES\n"\
"PRAIRIES DE LA TERRE, VOTRE PLANETE.\n"\
"\n"\
"VOUS VOUS DEMANDEZ CE QUI S'EST PASSE\n"\
"SUR TERRE PENDANT QUE VOUS AVEZ\n"\
"COMBATTU LE DEMON. HEUREUSEMENT,\n"\
"AUCUN GERME DU MAL N'A FRANCHI\n"\
"CETTE PORTE AVEC VOUS..."



// after level 6, put this:

#define FRNC1TEXT	"VOUS ETES AU PLUS PROFOND DE L'ASTROPORT\n" \
"INFESTE DE MONSTRES, MAIS QUELQUE CHOSE\n" \
"NE VA PAS. ILS ONT APPORTE LEUR PROPRE\n" \
"REALITE, ET LA TECHNOLOGIE DE L'ASTROPORT\n" \
"EST AFFECTEE PAR LEUR PRESENCE.\n" \
"\n"\
"DEVANT VOUS, VOUS VOYEZ UN POSTE AVANCE\n" \
"DE L'ENFER, UNE ZONE FORTIFIEE. SI VOUS\n" \
"POUVEZ PASSER, VOUS POURREZ PENETRER AU\n" \
"COEUR DE LA BASE HANTEE ET TROUVER \n" \
"L'INTERRUPTEUR DE CONTROLE QUI GARDE LA \n" \
"POPULATION DE LA TERRE EN OTAGE."

// After level 11, put this:

#define FRNC2TEXT	"VOUS AVEZ GAGNE! VOTRE VICTOIRE A PERMIS\n" \
"A L'HUMANITE D'EVACUER LA TERRE ET \n"\
"D'ECHAPPER AU CAUCHEMAR. VOUS ETES \n"\
"MAINTENANT LE DERNIER HUMAIN A LA SURFACE \n"\
"DE LA PLANETE. VOUS ETES ENTOURE DE \n"\
"MUTANTS CANNIBALES, D'EXTRATERRESTRES \n"\
"CARNIVORES ET D'ESPRITS DU MAL. VOUS \n"\
"ATTENDEZ CALMEMENT LA MORT, HEUREUX \n"\
"D'AVOIR PU SAUVER VOTRE RACE.\n"\
"MAIS UN MESSAGE VOUS PARVIENT SOUDAIN\n"\
"DE L'ESPACE: \"NOS CAPTEURS ONT LOCALISE\n"\
"LA SOURCE DE L'INVASION EXTRATERRESTRE.\n"\
"SI VOUS Y ALLEZ, VOUS POURREZ PEUT-ETRE\n"\
"LES ARRETER. LEUR BASE EST SITUEE AU COEUR\n"\
"DE VOTRE VILLE NATALE, PRES DE L'ASTROPORT.\n"\
"VOUS VOUS RELEVEZ LENTEMENT ET PENIBLEMENT\n"\
"ET VOUS REPARTEZ POUR LE FRONT."

// After level 20, put this:

#define FRNC3TEXT	"VOUS ETES AU COEUR DE LA CITE CORROMPUE,\n"\
"ENTOURE PAR LES CADAVRES DE VOS ENNEMIS.\n"\
"VOUS NE VOYEZ PAS COMMENT DETRUIRE LA PORTE\n"\
"DES CREATURES DE CE COTE. VOUS SERREZ\n"\
"LES DENTS ET PLONGEZ DANS L'OUVERTURE.\n"\
"\n"\
"IL DOIT Y AVOIR UN MOYEN DE LA FERMER\n"\
"DE L'AUTRE COTE. VOUS ACCEPTEZ DE\n"\
"TRAVERSER L'ENFER POUR LE FAIRE?"

// After level 29, put this:

#define FRNC4TEXT	"LE VISAGE HORRIBLE D'UN DEMON D'UNE\n"\
"TAILLE INCROYABLE S'EFFONDRE DEVANT\n"\
"VOUS LORSQUE VOUS TIREZ UNE SALVE DE\n"\
"ROQUETTES DANS SON CERVEAU. LE MONSTRE\n"\
"SE RATATINE, SES MEMBRES DECHIQUETES\n"\
"SE REPANDANT SUR DES CENTAINES DE\n"\
"KILOMETRES A LA SURFACE DE L'ENFER.\n"\
"\n"\
"VOUS AVEZ REUSSI. L'INVASION N'AURA.\n"\
"PAS LIEU. LA TERRE EST SAUVEE. L'ENFER\n"\
"EST ANEANTI. EN VOUS DEMANDANT OU IRONT\n"\
"MAINTENANT LES DAMNES, VOUS ESSUYEZ\n"\
"VOTRE FRONT COUVERT DE SUEUR ET REPARTEZ\n"\
"VERS LA TERRE. SA RECONSTRUCTION SERA\n"\
"BEAUCOUP PLUS DROLE QUE SA DESTRUCTION.\n"

// Before level 31, put this:

#define FRNC5TEXT	"FELICITATIONS! VOUS AVEZ TROUVE LE\n"\
"NIVEAU SECRET! IL SEMBLE AVOIR ETE\n"\
"CONSTRUIT PAR LES HUMAINS. VOUS VOUS\n"\
"DEMANDEZ QUELS PEUVENT ETRE LES\n"\
"HABITANTS DE CE COIN PERDU DE L'ENFER."

// Before level 32, put this:

#define FRNC6TEXT	"FELICITATIONS! VOUS AVEZ DECOUVERT\n"\
"LE NIVEAU SUPER SECRET! VOUS FERIEZ\n"\
"MIEUX DE FONCER DANS CELUI-LA!\n"

//
// Character cast strings F_FINALE.C
//
#define FRNCC_ZOMBIE	"ZOMBIE"
#define FRNCC_SHOTGUN	"TYPE AU FUSIL"
#define FRNCC_HEAVY	"MEC SUPER-ARME"
#define FRNCC_IMP		"DIABLOTIN"
#define FRNCC_DEMON	"DEMON"
#define FRNCC_LOST		"AME PERDUE"
#define FRNCC_CACO		"CACODEMON"
#define FRNCC_HELL		"CHEVALIER DE L'ENFER"
#define FRNCC_BARON	"BARON DE L'ENFER"
#define FRNCC_ARACH	"ARACHNOTRON"
#define FRNCC_PAIN		"ELEMENTAIRE DE LA DOULEUR"
#define FRNCC_REVEN	"REVENANT"
#define FRNCC_MANCU	"MANCUBUS"
#define FRNCC_ARCH		"ARCHI-INFAME"
#define FRNCC_SPIDER	"L'ARAIGNEE CERVEAU"
#define FRNCC_CYBER	"LE CYBERDEMON"
#define FRNCC_HERO		"NOTRE HEROS"

#define FRNHUSTR_E4M1 ENGHUSTR_E4M1
#define FRNHUSTR_E4M2 ENGHUSTR_E4M2
#define FRNHUSTR_E4M3 ENGHUSTR_E4M3
#define FRNHUSTR_E4M4 ENGHUSTR_E4M4
#define FRNHUSTR_E4M5 ENGHUSTR_E4M5
#define FRNHUSTR_E4M6 ENGHUSTR_E4M6
#define FRNHUSTR_E4M7 ENGHUSTR_E4M7
#define FRNHUSTR_E4M8 ENGHUSTR_E4M8
#define FRNHUSTR_E4M9 ENGHUSTR_E4M9

#define FRNPHUSTR_1 ENGPHUSTR_1
#define FRNPHUSTR_2 ENGPHUSTR_2
#define FRNPHUSTR_3 ENGPHUSTR_3
#define FRNPHUSTR_4 ENGPHUSTR_4
#define FRNPHUSTR_5 ENGPHUSTR_5
#define FRNPHUSTR_6 ENGPHUSTR_6
#define FRNPHUSTR_7 ENGPHUSTR_7
#define FRNPHUSTR_8 ENGPHUSTR_8
#define FRNPHUSTR_9 ENGPHUSTR_9
#define FRNPHUSTR_10 ENGPHUSTR_10
#define FRNPHUSTR_11 ENGPHUSTR_11
#define FRNPHUSTR_12 ENGPHUSTR_12
#define FRNPHUSTR_13 ENGPHUSTR_13
#define FRNPHUSTR_14 ENGPHUSTR_14
#define FRNPHUSTR_15 ENGPHUSTR_15
#define FRNPHUSTR_16 ENGPHUSTR_16
#define FRNPHUSTR_17 ENGPHUSTR_17
#define FRNPHUSTR_18 ENGPHUSTR_18
#define FRNPHUSTR_19 ENGPHUSTR_19
#define FRNPHUSTR_20 ENGPHUSTR_20
#define FRNPHUSTR_21 ENGPHUSTR_21
#define FRNPHUSTR_22 ENGPHUSTR_22
#define FRNPHUSTR_23 ENGPHUSTR_23
#define FRNPHUSTR_24 ENGPHUSTR_24
#define FRNPHUSTR_25 ENGPHUSTR_25
#define FRNPHUSTR_26 ENGPHUSTR_26
#define FRNPHUSTR_27 ENGPHUSTR_27
#define FRNPHUSTR_28 ENGPHUSTR_28
#define FRNPHUSTR_29 ENGPHUSTR_29
#define FRNPHUSTR_30 ENGPHUSTR_30
#define FRNPHUSTR_31 ENGPHUSTR_31
#define FRNPHUSTR_32 ENGPHUSTR_32

#define FRNTHUSTR_1 ENGTHUSTR_1
#define FRNTHUSTR_2 ENGTHUSTR_2
#define FRNTHUSTR_3 ENGTHUSTR_3
#define FRNTHUSTR_4 ENGTHUSTR_4
#define FRNTHUSTR_5 ENGTHUSTR_5
#define FRNTHUSTR_6 ENGTHUSTR_6
#define FRNTHUSTR_7 ENGTHUSTR_7
#define FRNTHUSTR_8 ENGTHUSTR_8
#define FRNTHUSTR_9 ENGTHUSTR_9
#define FRNTHUSTR_10 ENGTHUSTR_10
#define FRNTHUSTR_11 ENGTHUSTR_11
#define FRNTHUSTR_12 ENGTHUSTR_12
#define FRNTHUSTR_13 ENGTHUSTR_13
#define FRNTHUSTR_14 ENGTHUSTR_14
#define FRNTHUSTR_15 ENGTHUSTR_15
#define FRNTHUSTR_16 ENGTHUSTR_16
#define FRNTHUSTR_17 ENGTHUSTR_17
#define FRNTHUSTR_18 ENGTHUSTR_18
#define FRNTHUSTR_19 ENGTHUSTR_19
#define FRNTHUSTR_20 ENGTHUSTR_20
#define FRNTHUSTR_21 ENGTHUSTR_21
#define FRNTHUSTR_22 ENGTHUSTR_22
#define FRNTHUSTR_23 ENGTHUSTR_23
#define FRNTHUSTR_24 ENGTHUSTR_24
#define FRNTHUSTR_25 ENGTHUSTR_25
#define FRNTHUSTR_26 ENGTHUSTR_26
#define FRNTHUSTR_27 ENGTHUSTR_27
#define FRNTHUSTR_28 ENGTHUSTR_28
#define FRNTHUSTR_29 ENGTHUSTR_29
#define FRNTHUSTR_30 ENGTHUSTR_30
#define FRNTHUSTR_31 ENGTHUSTR_31
#define FRNTHUSTR_32 ENGTHUSTR_32

#define FRNE4TEXT ENGE4TEXT

#define FRNP1TEXT ENGP1TEXT
#define FRNP2TEXT ENGP2TEXT
#define FRNP3TEXT ENGP3TEXT
#define FRNP4TEXT ENGP4TEXT
#define FRNP5TEXT ENGP5TEXT
#define FRNP6TEXT ENGP6TEXT

#define FRNT1TEXT ENGT1TEXT
#define FRNT2TEXT ENGT2TEXT
#define FRNT3TEXT ENGT3TEXT
#define FRNT4TEXT ENGT4TEXT
#define FRNT5TEXT ENGT5TEXT
#define FRNT6TEXT ENGT6TEXT

//new strings
#define FRNV_INITSTR    "V_Init: allocate screens.\n"
#define FRNM_LDEFSTR    "M_LoadDefaults: Load system defaults.\n"
#define FRNZ_INITSTR    "Z_Init: Init zone memory allocation daemon. \n"
#define FRNW_INITSTR    "W_Init: Init WADfiles.\n"
#define FRNM_INITSTR    "M_Init: Init miscellaneous info.\n"
#define FRNR_INITSTR    "R_Init: Init DOOM refresh daemon - "
#define FRNP_INITSTR    "\nP_Init: Init Playloop state.\n"
#define FRNI_INITSTR    "I_Init: Setting up machine state.\n"
#define FRND_CHKNETSTR  "D_CheckNetGame: Checking network game status.\n"
#define FRNS_INITSTR    "S_Init: Setting up sound.\n"
#define FRNHU_INITSTR   "HU_Init: Setting up heads up display.\n"
#define FRNST_INITSTR   "ST_Init: Init status bar.\n"
#define FRNNETLISTEN    "listening for network start info...\n"
#define FRNNETSEND      "sending network start info...\n"
#define FRNTURBOSCLSTR  "turbo scale: %i%%\n"
#define FRNISTURBOSTR   "%s is turbo!"

#define FRNMODMSG\
	    "===========================================================================\n"\
	    "ATTENTION:  This version of DOOM has been modified.  If you would like to\n"\
	    "get a copy of the original game, call 1-800-IDGAMES or see the readme file.\n"\
	    "        You will not receive technical support for modified games.\n"\
	    "                      press enter to continue\n"\
	    "===========================================================================\n"
#define FRNNOSWMSG\
	    "===========================================================================\n"\
	    "             This version is NOT SHAREWARE, do not distribute!\n"\
	    "         Please report software piracy to the SPA: 1-800-388-PIR8\n"\
	    "===========================================================================\n"
#define FRNNOSWMSG2\
	    "===========================================================================\n"\
	    "                            Do not distribute!\n"\
	    "         Please report software piracy to the SPA: 1-800-388-PIR8\n"\
	    "===========================================================================\n"
#define FRNSWMSG\
	    "===========================================================================\n"\
	    "                                Shareware!\n"\
	    "===========================================================================\n"
#define FRNUDOOMSTART\
 "                         The Ultimate DOOM Startup v%i.%i                        "
#define FRNSHAREDOOMSTART\
 "                            DOOM Shareware Startup v%i.%i                        "
#define FRNREGDOOMSTART\
 "                            DOOM Registered Startup v%i.%i                       "
#define FRNDOOM2START\
 "                         DOOM 2: Hell on Earth v%i.%i                            "
#define FRNPLUTSTART\
 "                   DOOM 2: Plutonia Experiment v%i.%i                            "
#define FRNTNTSTART\
 "                     DOOM 2: TNT - Evilution v%i.%i                              "
#define FRNPUBDOOMSTART\
 "                     Public DOOM - v%i.%i                                        "



//these are unused.  They're just here for Deh compatibility
#define FRNI_SDPMI   "I_StartupDPMI\n"
#define FRNI_SMOUSE  "I_StartupMouse\n"
#define FRNI_SJOY    "I_StartupJoystick\n"
#define FRNI_SKEY    "I_StartupKeyboard\n"
#define FRNI_SSOUND  "I_StartupSound\n"
#define FRNI_STIMER  "I_StartupTimer()\n"
#define FRNMOUSEOFF  "Mouse: not present\n"
#define FRNMOUSEON   "Mouse: detected\n"
#define FRNDPMI1     "DPMI memory: 0x%x"
#define FRNDPMI2     ", 0x%x allocated for zone\n"
#define FRNCOMMVER   "\tcommercial version.\n"
#define FRNSHAREVER  "\tshareware version.\n"
#define FRNREGVER    "\tregistered version.\n"


#endif
//-----------------------------------------------------------------------------
//
// $Log:$
//
//-----------------------------------------------------------------------------


