all:
	@echo "Sorry, you need GNU make, vanilla UNIX make won't do."
	@echo "You can download it for free from ftp.gnu.org."
	@echo "Also GNU make already might be installed as gmake on your"
	@echo "system, additional to the vanilla UNIX make, so try this"
	@echo "out first."
